### ISSUE TITLE
Use of `DisableAutoSaveHistory: true` in readline impacts history behaviour

### ISSUE THREAD

**Issue by lewisthompson** [desertbit/grumble#31] opened 2021-03-11 05:23 UTC
Disabling readline's built-in history at https://github.com/desertbit/grumble/blob/4afcb1c3fcfccc7fa1abe6f523a6cfa33f71edd1/app.go#L369 and manually registering history at https://github.com/desertbit/grumble/blob/4afcb1c3fcfccc7fa1abe6f523a6cfa33f71edd1/app.go#L446-L451 has the negative consequence of not storing the most recently executed command as the most recent history item.

Step 1:

```
prompt> command1
ran command1
prompt> command2
ran command2
```

Expected: up arrow shows `command2`
Actual: up arrow shows `command2` ✅

Step 2:

```
prompt> command1
bck-i-search: comm
ran command1
```

Expected: up arrow shows `command1`
Actual: up arrow shows `command2` ❌

By disabling/removing the code above we get the expected behaviour which matches history from bash, zsh, etc.

**Comment by skaldesh** [comment] 2021-03-11 08:38
I have a question about your second step

> prompt> command1
bck-i-search: comm
ran command1

Did you type command1 in the prompt yourself and then started the back search? Or did you navigate to it by pressing arrow up twice?

**Comment by lewisthompson** [comment] 2021-03-11 19:17
Ah good question - not totally clear.  I did:

```
^R
comm
^R
```

**Comment by skaldesh** [comment] 2021-03-12 08:18
Ok, I tried to reproduce it with the grumble simple sample. Steps I did:  
```
go run ./sample/simple/main.go
foo >>
foo >> daemon true
`daemon true` executed
foo >> daemon false
`daemon false` executed
foo >>
Ctrl+r
bck_i_search: daem
Ctrl+r
\n
`daemon true` executed
```
When I press up arrow three times afterwards I see in this order:
* `daemon true`
* `daemon false`
* `daemon true`

I am not sure if I exactly did your steps. Can you reproduce the issue with the sample yourself?

**Comment by skaldesh** [comment] 2021-03-15 08:47
Could you print your system's configuration? OS, Kernel, etc.  
That would be helpful, thanks in advance

**Comment by skaldesh** [comment] 2021-08-03 08:56
Closing due to age, please reopen if necessary

**Closed by skaldesh** 2021-08-03 08:56 UTC
Labels: needs more info
